spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: tiger
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}

  # Spring Redis Configuration
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      timeToLive: 60000  # Default TTL for cache entries in milliseconds (optional)
      enableStatistics: false

cache:
  ttl:
    shortLivedCache: 60000  # 1 minute in milliseconds
    longLivedCache: 3600000  # 1 hour in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# Best logging jpa query
decorator:
  datasource:
    datasource-proxy:
      logging: slf4j
      multiline: false
      count-query: true
      slow-query:
        enable-logging: true
        log-level: warn
        threshold: 300

logging:
  level:
    net.ttddyy.dsproxy.listener: debug

