spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: tiger
    driverClassName: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true


  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      timeToLive: 60000  # Default TTL for cache entries in milliseconds (optional)
      enableStatistics: true

cache:
  ttl:
    shortLivedCache: 60000  # 1 minute in milliseconds
    longLivedCache: 3600000  # 1 hour in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE